# ------------------------------------------------------------------------
#
# Copyright 2019 WSO2, Inc. (http://wso2.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
#
# ------------------------------------------------------------------------

# Configuration for the APIM service broker

# Logging configuration
log:
  # log file path
  filePath: "server.log"
  # log level(info, debug, error, fatal)
  level: "info"

# HTTP server/client configuration
http:
  server:
    # basic Auth configuration for the service broker
    auth:
      username: "admin"
      password: "admin"

    # HTTPS configuration
    tls:
      # Enable HTTPS server
      enabled: false
      # private certificate for TLS
      key: "key.pem"
      # public certificate for TLS
      cert: "cert.pem"
    # host for server
    host: "0.0.0.0"
    # port for server
    port: 8444

  client:
    # if "true", doesn't validate the certificate for the APIM
    insecureCon: true
    # request timeout in seconds
    timeout: 30
    # minimum seconds for the back off policy
    minBackOff: 1
    # maximum seconds for the back off policy
    maxBackOff: 60
    # maximum retries
    maxRetries: 3

# APIM endpoints and credentials
apim:
  # Credentials for APIM
  username: "admin"
  password: "admin"
  # token endpoint
  tokenEndpoint: "https://localhost:8243"
  # dynamic client endpoint
  dynamicClientEndpoint: "https://localhost:9443"
  #dynamic client registration context
  dynamicClientRegistrationContext: "/client-registration/v0.14/register"
  # publisher endpoint
  publisherEndpoint: "https://localhost:9443"
  # publisher API context
  publisherAPIContext: "/api/am/publisher/v0.14/apis"
  # store endpoint
  storeEndpoint: "https://localhost:9443"
  # store Application API context
  storeApplicationContext: "/api/am/store/v0.14/applications"
  # store Subscription API Context
  storeSubscriptionContext: "/api/am/store/v0.14/subscriptions"
  # multiple Subscriptions context
  storeMultipleSubscriptionsContext: "/api/am/store/v0.14/subscriptions/multiple"
  # generate application context
  generateApplicationKeyContext: "/api/am/store/v0.14/applications/generate-keys"

# Database configuration
db:
  # database host
  host: 'localhost'
  # database port
  port: 3306
  # database username
  username: root
  # database password
  password: root123
  # database name
  database: broker
  # enable debug logs
  logMode:  false
